# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  namme: 'Windows Tests'
  vmImage: 'windows-2019'

steps:
- powershell: |
    #.\CI\02_install.ps1
    "[Running Pesters Scripts...]"
    #.\CI\tests.ps1
    pwd
    dir
    $path = (pwd).Path
    $FullPath = $(join-Path -Path $path -ChildPath "PSClassUtils\tests")
  displayName: 'Pwsh: Run Pester Script(s)'