# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

jobs:
- job: 'TestJob2019'
  pool:
    name: 'Windows 2019 Tests'
    vmImage: 'windows-2019'
  steps:
  - pwsh: |
      .\CI\02_install.ps1
      "[Running Pesters Scripts...]"
      .\CI\tests.ps1
    displayName: 'PSCore: Run Pester Script(s)'
  - powershell: |
      .\CI\02_install.ps1
      "[Running Pesters Scripts...]"
      .\CI\tests.ps1
    displayName: 'Powershell STANDARD: Run Pester Script(s)'
- job: 'TestJob2012R2'
  pool:
    name: 'Windows 2012 R2 Tests'
    vmImage: 'vs2015-win2012r2'
  steps:
  - powershell: |
      .\CI\02_install.ps1
      "[Running Pesters Scripts...]"
      .\CI\tests.ps1
    displayName: 'Powershell STANDARD: Run Pester Script(s)'
