# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  namme: 'Windows Tests'
  vmImage: 'windows-2019'

steps:
- pwsh: |
    #[System.Text.Encoding]::Default
    #get-culture | select *
    .\CI\02_install.ps1
    #"[Running Pesters Scripts...]"
    #.\CI\tests.ps1
  displayName: 'Pwsh: Run Pester Script(s)'